# Generated by Django 2.0.6 on 2018-07-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20180710_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
