# Generated by Django 3.1.8 on 2021-05-02 20:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0003_auto_20210502_1447'),
        ('timezone_management', '0005_auto_20210502_1447'),
        ('user_management', '0003_auto_20180710_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': 'site user', 'verbose_name_plural': 'site users'},
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='birthdate',
            field=models.DateField(blank=True, help_text='This is the help text', null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(help_text='This is the help text', max_length=200, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='city',
            field=models.ForeignKey(blank=True, help_text='This is the help text', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location_management.cities', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='country',
            field=models.ForeignKey(blank=True, help_text='This is the help text', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location_management.countries', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='gender',
            field=models.ForeignKey(blank=True, help_text='This is the help text', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.gender', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='This is the help text', max_length=128, null=True, region=None, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='This is the help text', null=True, upload_to='profile_pictures/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='state',
            field=models.ForeignKey(blank=True, help_text='This is the help text', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location_management.states', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='timezone',
            field=models.ForeignKey(blank=True, help_text='This is the help text', null=True, on_delete=django.db.models.deletion.SET_NULL, to='timezone_management.timezone', verbose_name='timezone'),
        ),
    ]
