# Generated by Django 2.0.6 on 2018-07-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'ordering': ['name']},
        ),
    ]
