# Generated by Django 3.1.8 on 2021-05-02 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0002_auto_20180710_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['name'], 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ['name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'ordering': ['name'], 'verbose_name': 'state', 'verbose_name_plural': 'states'},
        ),
        migrations.AlterField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(help_text='This is the help text', on_delete=django.db.models.deletion.CASCADE, to='location_management.countries', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='latitude',
            field=models.DecimalField(decimal_places=8, help_text='This is the help text', max_digits=10, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='longitude',
            field=models.DecimalField(decimal_places=8, help_text='This is the help text', max_digits=11, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(help_text='This is the help text', max_length=255, verbose_name='city name'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(help_text='This is the help text', on_delete=django.db.models.deletion.CASCADE, to='location_management.states', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='code',
            field=models.CharField(help_text='This is the help text', max_length=10, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(help_text='This is the help text', max_length=255, verbose_name='country name'),
        ),
        migrations.AlterField(
            model_name='states',
            name='code',
            field=models.CharField(help_text='This is the help text', max_length=10, verbose_name='state code'),
        ),
        migrations.AlterField(
            model_name='states',
            name='country',
            field=models.ForeignKey(help_text='This is the help text', on_delete=django.db.models.deletion.CASCADE, to='location_management.countries', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='states',
            name='name',
            field=models.CharField(help_text='This is the help text', max_length=255, verbose_name='state name'),
        ),
    ]
